application:
  job-name: importLibraryDataJob
  chunk-size: 2

spring:
  batch:
    job:
      enabled: false

  shell:
    interactive:
      enabled: true

  messages:
    basename: bundle
    fallback-to-system-locale: false

  datasource:
    url: jdbc:h2:mem:librarydb
    driver-class-name: org.h2.Driver
    initialization-mode: always
    schema: schema.sql
    data: data.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
      hibernate:

  data:
    mongodb:
      host: localhost
      port: 27017
      database: SpringBatch

logging:
  level:
    root: info
