application:
  locale: en_EN

spring:
  messages:
    basename: bundle
    fallback-to-system-locale: false

  datasource:
    url: jdbc:h2:mem:librarydb
    driver-class-name: org.h2.Driver
    initialization-mode: always
    schema: schema.sql
    data: data.sql