application:
  locale: en_EN

spring:
  messages:
    basename: bundle
    fallback-to-system-locale: false

  data:
    mongodb:
      host: localhost
      port: 27017
      database: library

    rest:
      basePath: /datarest

mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.library.changelogs

management:
  endpoints:
    web:
      exposure:
        include: health, logfile
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: info
  file:
    name: logfile.txt
